<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Users</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('admin', array('action' => 'user')); ?>"><li class="breadcrumb-item">Users Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Add</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Add Users Details</h3>
        </div>
        <div class="block-content">
            <div class="col-md-12 table-responsive" id="hide">
                <form name="userInformation" id="userInformation"  class="mb-5" action="<?php echo $this->url('admin', array('action' => 'add-user')); ?>" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Name<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control isRequired" id="name" name="name" placeholder="Enter the name" title="Please enter the name">
                        </div>

                        <label class="col-sm-2 col-form-label" for="">Role<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="roleName" name="roleName" title="Please select the role name">
                                <option value="">--Select--</option>
                                <?php foreach($roleResult as $role){?>
                                    <option value="<?php echo base64_encode($role['role_id']); ?>"><?php echo $role['role_name']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Email<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="email" class="form-control isRequired" id="email" name="email" placeholder="Enter the email" title="Please enter the email" onblur="checkNameValidation('user_details', 'username', this,null, 'The email that you entered already exists . Please try another name..');">
                        </div>

                        <label class="col-sm-2 col-form-label" for="">Password<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="password" class="form-control isRequired" id="password" name="password" placeholder="Enter the Password" title="Please enter the password">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Mobile<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="number" class="form-control isRequired" id="mobile" name="mobile" placeholder="Enter the mobile" title="Please enter the mobile">
                        </div>

                        <label class="col-sm-2 col-form-label" for="">Status<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="userStatus" name="userStatus" title="Please select the user status">
                                <option value="active">Active</option>
                                <option value="inactive">Inactive</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="row items-push">
                        <div class="col-lg-7 offset-lg-4">
                            <a href="<?php echo $this->url('admin', array('action' => 'user')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'userInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('userInformation').submit();
            }
        }
    }
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!= ''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", { tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0)
                {
                        alert(msg);
                        duplicateName = false;
                        document.getElementById(obj.id).value = "";
                }
                else {
                        duplicateName = true;
                }
            });
        }
    }
</script>
