<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Tyres</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('admin', array('action' => 'tyre')); ?>"><li class="breadcrumb-item">Tyres Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Add</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Add Tyres Details</h3>
        </div>
        <div class="block-content">
            <div class="col-md-12" id="hide">
                <form name="tyreInformation" id="tyreInformation"  class="mb-5" action="<?php echo $this->url('admin', array('action' => 'add-tyre')); ?>" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Tyre Type<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="tyreType" name="tyreType" title="Please select the tyre type" onchange="checkDiff(this);">
                                <option value="same" <?php echo($result['vehicle_id'] == $vehicle['vehicle_id'] )?'selected="selected"':''; ?>>Same</option>
                                <option value="different" <?php echo($result['vehicle_id'] == $vehicle['vehicle_id'] )?'selected="selected"':''; ?>>Different</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="js-wizard-simple block block block-rounded block-bordered">
                         <ul class="nav nav-tabs nav-tabs-block nav-justified" role="tablist">
                              <li class="nav-item">
                                   <a class="nav-link active" href="javascript:void()" id="step1" onclick="validateStep2()">Front</a>
                              </li>
                              <li class="nav-item different" style="display:none;">
                                   <a class="nav-link" href="javascript:void()" id="step2" onclick="validateStep1();">Back</a>
                              </li>
                         </ul>
                         <div class="block-content block-content-full tab-content" style="min-height: 300px;">
                            <div class="tab-pane active" id="wizard-progress-step1" role="tabpanel">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Select Vehicle<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <select class="form-control isRequired" id="vehicleId1" name="vehicleId[]" title="Please select the vehicle">
                                            <option value="">--Select--</option>
                                            <?php foreach($vehicleResult as $vehicle){?>
                                                <option value="<?php echo base64_encode($vehicle['vehicle_id']); ?>"><?php echo $vehicle['vehicle_no']; ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>

                                    <label class="col-sm-2 col-form-label" for="">Tyre<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <select class="form-control isRequired" id="tyre1" name="tyre[]" title="Please select the tyre">
                                            <option value="new">New</option>
                                            <option value="old">Old</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Tyre Brand<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control isRequired" id="tyreBrand1" name="tyreBrand[]" placeholder="Enter the brand" title="Please enter the brand">
                                    </div>

                                    <label class="col-sm-2 col-form-label" for="">Tyre Name<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control isRequired" id="tyreName1" name="tyreName[]" placeholder="Enter the name" title="Please enter the name">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Date Of Parchase</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="js-datepicker form-control" id="dateParchase1" name="dateParchase[]" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" placeholder="Enter the date of parchase" title="Please enter the date of parchase" readonly="readonly">
                                    </div>

                                    <label class="col-sm-2 col-form-label" for="">Tyre Size</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" id="tyreSize1" name="tyreSize[]" placeholder="Enter the size" title="Please enter the size">   
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Tyre Life Remaining</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" id="tyreLife1" name="tyreLife[]" placeholder="Enter the tyre life" title="Please enter the tyre life">
                                    </div>

                                    <label class="col-sm-2 col-form-label" for="">Tyre Side<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <select class="form-control isRequired" id="tyreSide1" name="tyreSide[]" title="Please select the tyre side">
                                            <option value="front">Front</option>
                                            <option value="back">Back</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Rim Size</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" id="rimSize1" name="rimSize[]" placeholder="Enter the rim size" title="Please enter the rim size">   
                                    </div>
                                </div>
                            </div>

                            <div class="tab-pane" id="wizard-progress-step2" role="tabpanel">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Select Vehicle<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <select class="form-control" id="vehicleId2" name="vehicleId[]" title="Please select the vehicle">
                                            <option value="">--Select--</option>
                                            <?php foreach($vehicleResult as $vehicle){?>
                                                <option value="<?php echo base64_encode($vehicle['vehicle_id']); ?>"><?php echo $vehicle['vehicle_no']; ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>

                                    <label class="col-sm-2 col-form-label" for="">Tyre<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <select class="form-control" id="tyre2" name="tyre[]" title="Please select the tyre">
                                            <option value="new">New</option>
                                            <option value="old">Old</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Tyre Brand<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" id="tyreBrand2" name="tyreBrand[]" placeholder="Enter the brand" title="Please enter the brand">
                                    </div>

                                    <label class="col-sm-2 col-form-label" for="">Tyre Name<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" id="tyreName2" name="tyreName[]" placeholder="Enter the name" title="Please enter the name">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Date Of Parchase</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="js-datepicker form-control" id="dateParchase2" name="dateParchase[]" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" placeholder="Enter the date of parchase" title="Please enter the date of parchase" readonly="readonly">
                                    </div>

                                    <label class="col-sm-2 col-form-label" for="">Tyre Size</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" id="tyreSize2" name="tyreSize[]" placeholder="Enter the size" title="Please enter the size">   
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Tyre Life Remaining</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" id="tyreLife2" name="tyreLife[]" placeholder="Enter the tyre life" title="Please enter the tyre life">
                                    </div>

                                    <label class="col-sm-2 col-form-label" for="">Tyre Side<span class="mandatory">*</span></label>
                                    <div class="col-sm-4">
                                        <select class="form-control" id="tyreSide2" name="tyreSide[]" title="Please select the tyre side">
                                            <option value="front">Front</option>
                                            <option value="back">Back</option>
                                        </select>
                                    </div>
                                </div>
                                                              
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="">Rim Size</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" id="rimSize2" name="rimSize[]" placeholder="Enter the rim size" title="Please enter the rim size">   
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <button type="button" class="btn btn-secondary btnHide" onclick="validateStep2()" style="display:none;"><i class="fa fa-angle-left mr-1"></i> Previous</button>
                    <button type="button" class="btn btn-secondary nxtBtn" onclick="validateStep1()" style=" float: right; display:none; ">Next <i class="fa fa-angle-right ml-1"></i></button>
                    <div class="row items-push">
                        <div class="col-lg-7 offset-lg-4 submit">
                            <a href="<?php echo $this->url('admin', array('action' => 'tyre')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'tyreInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('tyreInformation').submit();
            }
        }
    }
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!= ''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", { tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0)
                {
                        alert(msg);
                        duplicateName = false;
                        document.getElementById(obj.id).value = "";
                }
                else {
                        duplicateName = true;
                }
            });
        }
    }

    function validateStep1()
    {
        flag = deforayValidator.init({
            formId: 'tyreInformation'
        });
        if (flag) {
            $("#vehicleId2").addClass("isRequired");
            $("#ownerName2").addClass("isRequired");
            $("#tyre2").addClass("isRequired");
            $("#tyreBrand2").addClass("isRequired");
            $("#tyreName2").addClass("isRequired");
            // $("#dateParchase2").addClass("isRequired");
            // $("#tyreSize2").addClass("isRequired");
            // $("#tyreLife2").addClass("isRequired");
            $("#tyreSide2").addClass("isRequired");
            // $("#rimSize2").addClass("isRequired");

            $("#step1,#wizard-progress-step1").removeClass("active");
            $("#step2,#wizard-progress-step2").addClass("active");

            $(".btnHide").show();
            $(".nxtBtn").hide();
            $('.submit').show();
        }else{
            $('.submit').hide();
            $(".btnHide").hide();
        }
    }
    function validateStep2()
    {
        $("#vehicleId2").removeClass("isRequired");
        $("#ownerName2").removeClass("isRequired");
        $("#tyre2").removeClass("isRequired");
        $("#tyreBrand2").removeClass("isRequired");
        $("#tyreName2").removeClass("isRequired");
        // $("#dateParchase2").removeClass("isRequired");
        // $("#tyreSize2").removeClass("isRequired");
        // $("#tyreLife2").removeClass("isRequired");
        $("#tyreSide2").removeClass("isRequired");
        // $("#rimSize2").removeClass("isRequired");

        $("#step1,#wizard-progress-step1").addClass("active");
        $("#step2,#wizard-progress-step2").removeClass("active");

        $(".btnHide").hide();
        $(".nxtBtn").show();
        $('.submit').hide();
    }

    function checkDiff(obj){
        if(obj.value == 'different'){
            $('.different').show();
            $('.nxtBtn').show();
            $('.submit').hide();
        }else{
            $("#vehicleId2").removeClass("isRequired");
            $("#ownerName2").removeClass("isRequired");
            $("#tyre2").removeClass("isRequired");
            $("#tyreBrand2").removeClass("isRequired");
            $("#tyreName2").removeClass("isRequired");
            // $("#dateParchase2").removeClass("isRequired");
            // $("#tyreSize2").removeClass("isRequired");
            // $("#tyreLife2").removeClass("isRequired");
            $("#tyreSide2").removeClass("isRequired");
            // $("#rimSize2").removeClass("isRequired");

            $('.different').hide();
            $('.nxtBtn').hide();
            $('.submit').show();
        }
    }

    function selectOwner(obj){
        $('#ownerName2').val(obj.value);
        $('#ownerName2').prop('disabled',true);
    }

</script>
