<?php
    use Zend\Session\Container;
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Tyres Details</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="<?php echo $this->url('admin',array('action' => 'add-tyre'));?>" class="btn btn-primary pull-right" style="margin-top:-5px;"><i class="fa fa-plus"></i>&nbsp;Add New Tyre</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            
        </div>
        <div class="block-content block-content-full">
            <table id="tyreDataTable" class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th>Vehicle Number</th>
                        <th>Owner name</th>
                        <th>Tyre</th>
                        <th>Tyre Brand</th>
                        <th>Tyre Name</th>
                        <th>Tyre Side</th>
                        <th>Tyre Type</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="8" class="dataTables_empty">Loading data from server</td>
                    </tr>
                    <tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
    $(document).ready(function() {
    oTable = $('#tyreDataTable').dataTable( {
        "bAutoWidth": false,
        "bProcessing": true,
        "bServerSide": true,
        "aoColumns": [
                <?php echo $editAction;?>
        ],
        "sAjaxSource": "<?php echo $this->url('admin',array('action' => 'tyre')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    } );

    } );
</script>